server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: postgres
    password: ${DB_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE

kakao:
  api:
    key: ${KAKAO_API_KEY}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE