spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: postgres
    password: ${DB_PASSWORD}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE